# -*- coding: utf-8 -*-
"""Proyek Analisis Data Dicoding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fP6VY9uudbvDX7_4YlcIwWQwugfBuNZ9

# Proyek Analisis Data: [Input Nama Dataset]
- Nama: Reinhart Jens Robert
- Email: reinhartrobert23@gmail.com
- ID Dicoding: Reinhart Jens Robert

## Menentukan Pertanyaan Bisnis

question 1 = "Bagaimana distribusi penjual di berbagai negara bagian?"
question 2 = "Apakah ada konsentrasi penjual di kota-kota tertentu?"

## Import Semua Packages/Library yang Digunakan
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

# Load Dataset
file_path = "/content/drive/MyDrive/dicoding/E-Commerce Public Dataset/sellers_dataset.csv"  # Sesuaikan dengan lokasi file Anda
df = pd.read_csv(file_path)

"""## Data Wrangling & Gathering Data"""

print("Informasi dataset:\n", df.info())
print("\nDeskripsi statistik:\n", df.describe())
print("\nJumlah nilai unik per kolom:\n", df.nunique())

"""# Insight 1: Banyak penjual berbagi kode pos yang sama
# Insight 2: Sebaran penjual mungkin tidak merata di berbagai wilayah

### Assessing Data
"""

print("\nCek missing values:\n", df.isnull().sum())
print("\nCek data duplikat:\n", df.duplicated().sum())

"""# Insight 1: Tidak ada nilai yang hilang
# Insight 2: Tidak ada data duplikat, sehingga data tidak memerlukan pembersihan lebih lanjut

### Cleaning Data
"""

df['seller_city'] = df['seller_city'].str.lower()
df['seller_state'] = df['seller_state'].str.upper()

"""# Insight 1: Standarisasi nama kota dapat membantu analisis lebih akurat
# Insight 2: Negara bagian telah distandarisasi untuk menghindari inkonsistensi

## Exploratory Data Analysis (EDA)

### Explore ...
"""

# Distribusi penjual berdasarkan negara bagian
state_counts = df['seller_state'].value_counts()
plt.figure(figsize=(12, 6))
sns.barplot(x=state_counts.index, y=state_counts.values, palette='viridis')
plt.xticks(rotation=45)
plt.title("Distribusi Penjual di Berbagai Negara Bagian")
plt.xlabel("Negara Bagian")
plt.ylabel("Jumlah Penjual")
plt.show()

"""# Insight 1: Negara bagian tertentu memiliki lebih banyak penjual
# Insight 2: Ada beberapa negara bagian dengan jumlah penjual sangat sedikit

## Visualization & Explanatory Analysis
"""

# Kota dengan jumlah penjual terbanyak
top_cities = df['seller_city'].value_counts().head(10)
plt.figure(figsize=(12, 6))
sns.barplot(x=top_cities.index, y=top_cities.values, palette='coolwarm')
plt.xticks(rotation=45)
plt.title("10 Kota dengan Jumlah Penjual Terbanyak")
plt.xlabel("Kota")
plt.ylabel("Jumlah Penjual")
plt.show()

"""## Analisis Lanjutan (Opsional)"""

# Analisis Lanjutan: Distribusi Penjual berdasarkan Kode Pos
postal_counts = df['seller_zip_code_prefix'].value_counts().head(10)

# Visualisasi 10 Kode Pos dengan Jumlah Penjual Terbanyak
plt.figure(figsize=(12, 6))
sns.barplot(x=postal_counts.index, y=postal_counts.values, palette='Blues_r')
plt.xticks(rotation=45)
plt.title("10 Kode Pos dengan Jumlah Penjual Terbanyak")
plt.xlabel("Kode Pos")
plt.ylabel("Jumlah Penjual")
plt.show()

# Insight tambahan:
# 1. Beberapa kode pos memiliki konsentrasi penjual yang sangat tinggi, yang mungkin menunjukkan area bisnis yang berkembang.
# 2. Sebaran penjual yang terkonsentrasi dalam beberapa kode pos tertentu dapat menjadi indikator pusat distribusi atau area industri utama.

"""## Conclusion

- Conclution pertanyaan 1 = Distribusi penjual tidak merata di berbagai negara bagian. Beberapa negara bagian menjadi pusat aktivitas perdagangan dengan jumlah penjual yang lebih tinggi, sedangkan beberapa lainnya memiliki jumlah penjual yang lebih sedikit. Hal ini bisa mencerminkan faktor ekonomi, demografi, atau infrastruktur yang mendukung aktivitas perdagangan di wilayah tertentu.
- Conclution pertanyaan 2 =Konsentrasi penjual sangat bervariasi di berbagai kota. Kota-kota besar cenderung memiliki lebih banyak penjual, yang menandakan aktivitas perdagangan lebih tinggi dan pasar yang lebih besar. Kota-kota dengan sedikit penjual mungkin memiliki hambatan dalam akses pasar atau daya beli yang lebih rendah. Analisis ini dapat membantu dalam perencanaan ekspansi bisnis dan strategi pemasaran yang lebih efektif.
"""